/**
 * The canonical origin for the deployed site. Everything SEO-related derives
 * from it: the canonical link, the hreflang alternates, the Open Graph and
 * Twitter URLs, the JSON-LD, and public/sitemap.xml + public/robots.txt
 * (regenerated by `npm run build`).
 *
 * No trailing slash.
 */
export const SITE_URL = 'https://omar-borhom.vercel.app';

/** Absolute URL — social crawlers reject relative og:image values. */
export const OG_IMAGE = `${SITE_URL}/og.png`;
